### ISSUE TITLE
emax/emin potential typo

### ISSUE THREAD

**Issue by mmikaitis** [north-numerical-computing/cpfloat#2]
Probably line 1202 was meant to say params.emin = DEFEMIN; because params.emax is already set on line 1201.

https://github.com/north-numerical-computing/cpfloat/blob/7dabbe104f7849ae3de28da74956c690afb506ee/src/cpfloat_template.h#L1201-L1202

**Comment by mfasi** [comment]
It definitely looks like a bug. Not hard to fix, I'd say.

**Comment by mmikaitis** [comment]
Pushed to dev.
