### ISSUE TITLE
Documentation about scripts needed to run tests locally

### ISSUE THREAD

**Issue by mmikaitis** [north-numerical-computing/cpfloat#5]
This is not an issue in the code but more on the documentation side. I am putting it here so that we don't forget to address it at some point.

I think we need to provide some information in README on the testing framework and what dependencies need to be installed.

I tried to set it up on macOS and I noticed that I am missing:

check
checkmk
subunit
rt

Finding these packages is quite difficult since their names are quite generic. We could provide links (and their full names, short descriptions) to the sources of these packages in README which may help. I was able to easily install check and checkmk through Homebrew but I could not find subunit there and had to build it from source. As for rt, I still do not know what it is (perhaps the Request Tracker https://rt-wiki.bestpractical.com/wiki/ManualInstallation).

**Comment by mfasi** [comment]
Thanks for the report.

`-lrt` links against `librt`, and I don't think this flag is necessary, as `librt` is part of `libc` on Linux and doesn't seem to work on Mac.

Can you try to run the `Makefile` after removing both `-lsubunit` and `-lrt`? I expect the code to work anyway.

I'll concurrently test in Linux. If it works on both, I think it's safe to remove those two flags.

**Comment by mfasi** [comment]
I do need `-lsubunit` on Linux, but `-lrt` is unnecessary.

**Comment by mmikaitis** [comment]
Thank you @mfasi. Are we OK to remove -lrt? The other dependencies may addressed in the documentation for the developers' information looking to run make mtest/ctest/otest.

**Comment by mfasi** [comment]
Yes. I don't see any reason to keep it.

**Comment by mmikaitis** [comment]
Removed `-lrt` on dev branch.

**Comment by mfasi** [comment]
I've opened a pull request (#8) to fix the documentation. Is there anything else to address re. this issue?

**Comment by mmikaitis** [comment]
Thanks. I think checkmk should be added to the "Developer Dependencies" in README.md.

**Comment by mmikaitis** [comment]
> [`checkmk`](https://github.com/libcheck/check/tree/master/checkmk) is part of the check unit testing framework. I can change the relevant paragraph to:
> 
> > The unit tests for the C implementation in `test/cpfloat_test.ts` require the [check unit testing framework for C](https://libcheck.github.io/check), including the [`checkmk`](https://github.com/libcheck/check/tree/master/checkmk) script, and the [subunit protocol](https://github.com/testing-cabal/subunit).
> 
> Would this work?

Looks good; does checkmk come automatically with check? If so, we may need to state it explicitly. I also have checkmake installed, but I don't recall if that was part of setting up CPFloat or something else.

**Comment by mfasi** [comment]
If you compile `check` from sources, it comes automatically with `check`. On Debian, the script also comes as part of `check`

```bash
$ dpkg -S checkmk
check:amd64: /usr/share/man/man1/checkmk.1.gz
check:amd64: /usr/bin/checkmk
$ dpkg -S libcheck
check:amd64: /usr/lib/x86_64-linux-gnu/libcheck_pic.a
check:amd64: /usr/lib/x86_64-linux-gnu/libcheck.a
```

I'm not sure about MacOS, though. It might not come with the pre-packaged binaries.

**Comment by mmikaitis** [comment]
> If you compile `check` from sources, it comes automatically with `check`. On Debian, the script also comes as part of `check`
> 
> ```shell
> $ dpkg -S checkmk
> check:amd64: /usr/share/man/man1/checkmk.1.gz
> check:amd64: /usr/bin/checkmk
> $ dpkg -S libcheck
> check:amd64: /usr/lib/x86_64-linux-gnu/libcheck_pic.a
> check:amd64: /usr/lib/x86_64-linux-gnu/libcheck.a
> ```
> 
> I'm not sure about MacOS, though. It might not come with the pre-packaged binaries.

Probably it does not given that I listed it on this issue at the beginning. The modification looks good to me!
