### ISSUE TITLE
Referencing standards and specifications

### ISSUE THREAD

**Issue by mfasi** [north-numerical-computing/cpfloat#9]
In `README.md` we currently mention the IEEE 754 standard the the OFP8 specification, but we don't have links to them and they don't appear in the **References** section. The former is well known – the latter not as much.

Should we therefore include a citation, or at least a link? What would be the most suitable resource to point to?

**Comment by mmikaitis** [comment]
Yes, we should add them to the reference list. The OCP standard I believe is at https://www.opencompute.org/documents/ocp-8-bit-floating-point-specification-ofp8-revision-1-0-2023-12-01-pdf-1
